### ISSUE TITLE
Character limit increase for input source files when mapping

### ISSUE THREAD

**Issue by agamboa23** [RMLio/rmleditor-ce#1]
### Issue type: :unicorn: Feature
Rise the character limit for file serializations and minimize them. 

### Description
The 2 MB limitation per file is hard to reach since it is more likely to first hit the 5k character limitation per file when the file is serialized for the api (At least for Json Files). The API can handle the longer strings. It could also be useful to indicate when the validation is hit, currently only the the following error pops up when the characters limit is met using Files:

***

Problem with RMLMapper:
------------------------------------------------------
Internal server when executing the remote RMLMapper

***

The character limit is being applied on the client side before its request to the /execute endpoint of the RMLMapper Web API. The incomplete source parameter causes the system to prompt an error on the rmlmapper-java-wrapper-js module since it fails to parse it, creating a server error on the API.

Minimizing the json on the serialization would also be very helpful to keep the string as small as possible. All the mentioned exceptions were only tested with Json Files. 

### Why it is useful
Would allow to reach the intended 2mb per file limit and allow for better use of the RMLeditor community edition. If json minification is applied on the serialization, would also help not to require some pre-minification when uploading the source files.

### Existing features it breaks
Could break the API side without any limitation or reach the POST request body limit.

**Comment by pheyvaer** [comment]
Hi @agamboa23 

Thanks for creating the issue. We will remove the character limitation and only keep the filesize limitation.

**Comment by pheyvaer** [comment]
Hi @agamboa23,

Sorry for the super late reply, but we fixed this a while ago already. Just didn't reply to this issue yet.
