### ISSUE TITLE
How to handle json non objects array

### ISSUE THREAD

**Issue by agamboa23** [RMLio/rmleditor-ce#3]
### Issue type: :question: Question

If I have a simple json as following:

`{
  "id": "0",
  "values": ["A", "B", "C"]
}`

I am trying to map a new entity per element in the values array. I can successfully select $ as the iterator and use the rml:reference {values.[*]} to create attributes (as shown in the test samples of the mapper source code) but cannot obtain the same results if trying to map to entities. 

In the following image, the top one works, but the bottom one just maps the first element of the list:

![image](https://user-images.githubusercontent.com/4205724/107690094-f45de880-6ca9-11eb-830b-a8e33cea4fae.png)

Results:
![image](https://user-images.githubusercontent.com/4205724/107690177-0e97c680-6caa-11eb-839c-083f8db2067d.png)

Note: Thank you very much for the support, your tool has been incredibly useful on my research and hope to keep using it in the future.

**Comment by ghost** [comment]
Hi and thank you for using RML and the RMLEditor,

Creating subjects directly from JSON array values is a known issue in using RML with JSONPath. If a solution becomes available we will update the issue [here](https://github.com/RMLio/rmlmapper-java/issues/95). 

Closing this issue as it is more related to the language and mapper than to the editor.
