### ISSUE TITLE
Does RML Editor support nested array of objects within an array of objects?

### ISSUE THREAD

**Issue by anushalihala** [RMLio/rmleditor-ce#6]
### Issue type: :question: Question

Basically something like this:

Pure RML example: https://github.com/RMLio/RML-Mapper/issues/37 
YARRRML example: https://github.com/RMLio/yarrrml-parser/issues/67

**Comment by bjdmeest** [comment]
RMLEditor depends on RML, and executes the generation using RMLMapper-java. So, if I understand this case, this is not an issue with the RMLEditor, but rather a question on how to use RML. Could you create a new issue at https://github.com/kg-construct/rml-questions/discussions ? I would expect the answer to be similar to https://github.com/RMLio/yarrrml-parser/issues/67#issuecomment-614669254

**Comment by anushalihala** [comment]
thanks :)
